# Generated by Django 4.2 on 2024-05-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.IntegerField(blank=True, choices=[(2, 'через день'), (4, 'каждый четвертый день'), (3, 'каждый третий день'), (5, 'каждый пятый день'), (7, 'каждую неделю'), (1, 'каждый день'), (6, 'каждый шестой день')], default=1, null=True, verbose_name='периодичность'),
        ),
    ]
